# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'SuperChatApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SuperChatApp
  
  # Install Fluent UI
  pod 'MicrosoftFluentUI'
  
  # Install King fisher to load image from url
  pod 'Kingfisher', '~> 7.0'

end
